###
# @no-log
GET http://localhost:8080/books?year=1949

###
# @no-log
POST http://localhost:8080/customers
Content-Type: application/json

{
  "id": 1,
  "name": "Test Customer 1"
}

###
# @no-log
GET http://localhost:8080/customers
